[project]
name = "rag-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "fsspec==2026.7.0",
    "llama-index==0.14.23",
    "llama-index-core==0.14.24",
    "llama-index-embeddings-openai==0.6.0",
    "llama-index-instrumentation==0.6.0",
    "llama-index-llms-openai==0.7.10",
    "llama-index-llms-openai-like==0.7.2",
    "llama-index-llms-openrouter==0.5.1",
    "llama-index-vector-stores-qdrant==0.10.2",
    "llama-index-workflows==2.23.3",
    "openai==2.54.0",
    "python-dotenv==1.2.2",
    "qdrant-client==1.18.0",
]
